### ISSUE TITLE
foreman-installer

### ISSUE THREAD

**Issue by jmakanjuola** [theforeman/foreman_setup#16]
When I ran foreman-installer 

Here is the result:

/usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- kafo (LoadError)
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/sbin/foreman-installer:5:in `<main>'

**Comment by mmoll** [comment]
I suspect, this can get closed? :)

**Comment by GuanHitam** [comment]
I had the same symptoms and it was caused by having uppercase characters in the hostname that Foreman was not happy about. Solved by renaming COSBuildServer.zolder.pem into cosbuildserver.zolder for the pem locations in the config file /usr/share/foreman-proxy/config/settings.yml. 
'foreman_url' I kept having uppercase chars. 
inside '/usr/share/foreman-proxy/config/settings.yml ':
:foreman_url: https://COSBuildServer.zolder
:ssl_certificate: /var/lib/puppet/ssl/certs/cosbuildserver.zolder.pem
:ssl_private_key: /var/lib/puppet/ssl/private_keys/cosbuildserver.zolder.pem

Then start the service:
/bin/systemctl start foreman-proxy
Worked for me.

**Comment by smitjainsj** [comment]
It did fixed for me  :+1: 

error : `require': cannot load such file -- kafo (LoadError)
 rvm use system

**Comment by AlexisLessard** [comment]
While i don't get the error anymore (thx btw) I still can't install foreman because my system version of ruby is 2.0.0 and some dependencies require 2.2.2. That's why I used rvm. I'll have to install it manually.
